

#ifndef ASS_H
#define ASS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <libavcodec/avcodec.h>
#include <libavutil/bprint.h>


#define ASS_DIALOGUE_STRING  "Dialogue: 0,0:00:00.00,0:01:00.00,Default,,0000,0000,0000,,%s"
#define ASS_HEADER_STRING \
"[Script Info]\r\n"\
"; Script generated by FFmpeg/Lavc%s\r\n"\
"ScriptType: v4.00+\r\n"\
"PlayResX: %d\r\n"\
"PlayResY: %d\r\n"\
"\r\n"\
"[V4+ Styles]\\r\\n"\
"Format: Name, "\
"Fontname, Fontsize, "\
"PrimaryColour, SecondaryColour, OutlineColour, BackColour, "\
"Bold, Italic, Underline, StrikeOut, "\
"ScaleX, ScaleY, "\
"Spacing, Angle, "\
"BorderStyle, Outline, Shadow, "\
"Alignment, MarginL, MarginR, MarginV, "\
"Encoding\r\n"\
"Style: "\
"Default,"\
"%s,%d,"\
"&H%x,&H%x,&H%x,&H%x,"\
"%d,%d,%d,0,"\
"100,100,"\
"0,0,"\
"%d,1,0,"\
"%d,10,10,10,"\
"0\r\n"\
"\r\n"\
"[Events]\r\n"\
"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n"

	//Dialogue: 0,0:00:00.00,0:01:00.00,Default,,0000,0000,0000,,text

#define ASS_DEFAULT_PLAYRESX 100
#define ASS_DEFAULT_PLAYRESY 100

#define ASS_DEFAULT_FONT        "Arial"
#define ASS_DEFAULT_FONT_SIZE   32
#define ASS_DEFAULT_COLOR       0xffffff
#define ASS_DEFAULT_BACK_COLOR  0
#define ASS_DEFAULT_BOLD        0
#define ASS_DEFAULT_ITALIC      0
#define ASS_DEFAULT_UNDERLINE   0
#define ASS_DEFAULT_ALIGNMENT   2
#define ASS_DEFAULT_BORDERSTYLE 1

	int
	ass_subtitle_header(
		AVCodecContext *avctx,
		int palyresx, int palyresy,
		const char *font, int font_size,
		int color, int back_color,
		int bold, int italic, int underline,
		int border_style, int alignment
		);

	int
	ass_subtitle_header_default(AVCodecContext *avctx);

	int
	ass_add_rect (AVSubtitle *sub, const char *text);

#ifdef __cplusplus
}
#endif

#endif /* ASS_H */

