

#ifndef ASS_H
#define ASS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <libavcodec/avcodec.h>
#include <libavutil/bprint.h>
#include <ass/ass.h>


#define ASS_DIALOGUE_STRING  "Dialogue: 0,0:00:00.00,0:01:00.00,Default,,0000,0000,0000,,%s"

#define ASS_TRACK_STRING \
"[Script Info]\r\n"\
"; Script generated by FFmpeg/Lavc%s\r\n"\
"ScriptType: v4.00+\r\n"\
"PlayResX: %d\r\n"\
"PlayResY: %d\r\n"\
"\r\n"\
"[V4+ Styles]\r\n"\
"Format: Name, "\
"Fontname, Fontsize, "\
"PrimaryColour, SecondaryColour, OutlineColour, BackColour, "\
"Bold, Italic, Underline, StrikeOut, "\
"ScaleX, ScaleY, "\
"Spacing, Angle, "\
"BorderStyle, Outline, Shadow, "\
"Alignment, MarginL, MarginR, MarginV, "\
"Encoding\r\n"\
"Style: "\
"Default,"\
"%s,%d,"\
"&H%x,&H%x,&H%x,&H%x,"\
"%d,%d,%d,0,"\
"100,100,"\
"0,0,"\
"%d,1,0,"\
"%d,10,10,10,"\
"0\r\n"\
"\r\n"\
"[Events]\r\n"\
"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n"\
"Dialogue: 0,0:00:00.00,0:01:00.00,Default,,0000,0000,0000,,%s\r\n"


#define ASS_DEFAULT_PLAYRESX 100
#define ASS_DEFAULT_PLAYRESY 100

#define ASS_DEFAULT_FONT        "Arial"
#define ASS_DEFAULT_FONT_SIZE   32
#define ASS_PRIMARY_COLOR       0xffffff
#define ASS_SECONDARY_COLOR     0xffffff
#define ASS_OUTLINE_COLOR       0
#define ASS_BACK_COLOR          0
#define ASS_DEFAULT_BOLD        0
#define ASS_DEFAULT_ITALIC      0
#define ASS_DEFAULT_UNDERLINE   0
#define ASS_DEFAULT_ALIGNMENT   2
#define ASS_DEFAULT_BORDERSTYLE 1

	void 
	ass_init(int width, int height);
	ASS_Image*
	ass_get_track(const char *sub);
	int
	ass_add_sub(AVFrame *frame);

#ifdef __cplusplus
}
#endif

#endif /* ASS_H */

