#ifndef SUB_H
#define SUB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <libavcodec/avcodec.h>
#include <libavutil/bprint.h>
#include <ass/ass.h>


#define ASS_DIALOGUE_STRING  "Dialogue: 0,0:00:00.00,0:01:00.00,Default,,0000,0000,0000,,%s"

#define ASS_TRACK_STRING \
"[Script Info]\r\n"\
"; Script generated by FFmpeg/Lavc%s\r\n"\
"ScriptType: v4.00+\r\n"\
"PlayResX: %d\r\n"\
"PlayResY: %d\r\n"\
"\r\n"\
"[V4+ Styles]\r\n"\
"Format: Name, "\
"Fontname, Fontsize, "\
"PrimaryColour, SecondaryColour, OutlineColour, BackColour, "\
"Bold, Italic, Underline, StrikeOut, "\
"ScaleX, ScaleY, "\
"Spacing, Angle, "\
"BorderStyle, Outline, Shadow, "\
"Alignment, MarginL, MarginR, MarginV, "\
"Encoding\r\n"\
"Style: "\
"Default,"\
"%s,%d,"\
"&H00FFFFFF,&H00000000,&H00070707,&H00000000,"\
"0,0,0,0,"\
"100,100,"\
"1,0,"\
"0,2,0,"\
"2,10,10,10,"\
"1\r\n"\
"\r\n"\
"[Events]\r\n"\
"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n"\
"Dialogue: 0,0:00:00.00,0:01:00.00,Default,,0000,0000,0000,,%s\r\n"

#define ASS_DEFAULT_FONT        "Arial"
#define ASS_DEFAULT_FONT_SIZE   16
#define ASS_DEFAULT_TEXT        ""

	void
	sub_destroy(void);
	void 
	sub_init(int width, int height);
	int
	sub_draw(AVFrame *frame, const char* sub);

#ifdef __cplusplus
}
#endif

#endif /* SUB_H */

