#include "libavutil/avstring.h"
#include "ass.h"

static char* ass_get_dialog (int readorder, int layer, const char *style, const char *speaker, const char *text);
static int make_tc (uint64_t ms, int *tc);

int
ass_subtitle_header (
		AVCodecContext *avctx,
		const char *font,
		int font_size,
		int color,
		int back_color,
		int bold,
		int italic,
		int underline,
		int border_style,
		int alignment) {

	avctx->subtitle_header = (uint8_t*)av_asprintf(
			"[Script Info]\r\n"
			"; Script generated by FFmpeg/Lavc%s\r\n"
			"ScriptType: v4.00+\r\n"
			"PlayResX: %d\r\n"
			"PlayResY: %d\r\n"
			"\r\n"
			"[V4+ Styles]\r\n"

			/* ASSv4 header */
			"Format: Name, "
			"Fontname, Fontsize, "
			"PrimaryColour, SecondaryColour, OutlineColour, BackColour, "
			"Bold, Italic, Underline, StrikeOut, "
			"ScaleX, ScaleY, "
			"Spacing, Angle, "
			"BorderStyle, Outline, Shadow, "
			"Alignment, MarginL, MarginR, MarginV, "
			"Encoding\r\n"

			"Style: "
			"Default,"             /* Name */
			"%s,%d,"               /* Font{name,size} */
			"&H%x,&H%x,&H%x,&H%x," /* {Primary,Secondary,Outline,Back}Colour */
			"%d,%d,%d,0,"          /* Bold, Italic, Underline, StrikeOut */
			"100,100,"             /* Scale{X,Y} */
			"0,0,"                 /* Spacing, Angle */
			"%d,1,0,"              /* BorderStyle, Outline, Shadow */
			"%d,10,10,10,"         /* Alignment, Margin[LRV] */
			"0\r\n"                /* Encoding */

			"\r\n"
			"[Events]\r\n"
			"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n",
			!(avctx->flags & AV_CODEC_FLAG_BITEXACT) ? AV_STRINGIFY(LIBAVCODEC_VERSION) : "",
			ASS_DEFAULT_PLAYRESX, ASS_DEFAULT_PLAYRESY,
			font, font_size, color, color, back_color, back_color,
			-bold, -italic, -underline, border_style, alignment);

	if (!avctx->subtitle_header)
		return AVERROR(ENOMEM);
	avctx->subtitle_header_size = strlen((const char*)avctx->subtitle_header);
	return 0;
}

int
ass_subtitle_header_default (AVCodecContext *avctx) {
	return ass_subtitle_header(avctx, ASS_DEFAULT_FONT,
			ASS_DEFAULT_FONT_SIZE,
			ASS_DEFAULT_COLOR,
			ASS_DEFAULT_BACK_COLOR,
			ASS_DEFAULT_BOLD,
			ASS_DEFAULT_ITALIC,
			ASS_DEFAULT_UNDERLINE,
			ASS_DEFAULT_BORDERSTYLE,
			ASS_DEFAULT_ALIGNMENT);
}

static char*
ass_get_dialog (int readorder, int layer, const char *style, const char *speaker, const char *text) {
	return av_asprintf("Dialogue: %d,%d,%s,%s,0,0,0,,%s",
			readorder, layer, style ? style : "Default",
			speaker ? speaker : "", text);
}

static int
make_tc (uint64_t ms, int *tc) {
	static const int tc_divs[3] = { 1000, 60, 60 };
	int i;
	for (i = 0; i < 3; i++) {
		tc[i] = ms % tc_divs[i];
		ms /= tc_divs[i];
	}
	tc[3] = ms;
	return ms > 99;
}

int
ass_add_rect (AVSubtitle *sub, const char *text) {
	char *ass_str;
	AVSubtitleRect **rects;

	rects = av_realloc_array(sub->rects, (sub->num_rects + 1), sizeof (*sub->rects));
	if (!rects)
		return AVERROR(ENOMEM);
	sub->rects = rects;
	rects[sub->num_rects] = av_mallocz(sizeof (*rects[0]));
	if (!rects[sub->num_rects])
		return AVERROR(ENOMEM);
	rects[sub->num_rects]->type = SUBTITLE_ASS;
	ass_str = ass_get_dialog(0, 0, NULL, NULL, text);
	if (!ass_str)
		return AVERROR(ENOMEM);
	rects[sub->num_rects]->ass = ass_str;
	sub->num_rects++;
	return 0;
}